#!/usr/bin/python3

import sys
import time

def factorize(num):
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return (i, num // i)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit()

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as file:
            lines = file.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()

    start = time.time()


    for line in lines:
        num = int(line.strip())
        factors = factorize(num)
        if factors:
            print(f"{num} = {factors[1]} * {factors[0]}")

        if time.time() - start > 5:
            exit()

