#!/usr/bin/python3

import sys
import time
import random
from math import sqrt, ceil

def prime(n):
    if n < 2:
        return False
    for i in range(2, int(sqrt(n) + 1)):
    	if n % i == 0:
            return False
    return True

def primefactor(num):
    pfactors = []
    while num % 2 == 0:
        pfactors.append(2)
        num //= 2
    i = 3
    while i <= sqrt(num):
        if num % i == 0:
            pfactors.append(i)
            num //= i
        else:
            i += 2

    if num > 2:
        pfactors.append(num)
    if len(pfactors) == 1:
        p = pfactors[0]
        q = num // p
        return (p, q)

    else:
        pq = []
        for factor in pfactors:
            if prime(factor):
                 pq.append(factor)
            else:
                p, q = primefactor(factor)
                pq.append(p)
                pq.append(q)
        return tuple(pq)
    
input_file = sys.argv[1]


with open(input_file, 'r') as file:
    line = file.readline()
    rsa = [int(line.strip())]
    
start = time.time()

for i in rsa:
    p, q = primefactor(i)
    print(f"{i}={q}*{p}")

end = time.time()
